<?php

namespace Burut\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BaseRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRowRepository extends EntityRepository
{
}
