<?php

namespace Burut\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FieldTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldTypeRepository extends EntityRepository
{
}
